fix: use_sf and use_sfdx tests

diff --git a/action-command/action.yml b/action-command/action.yml
--- a/action-command/action.yml
+++ b/action-command/action.yml
@@ -52,8 +52,15 @@ runs:
       run: |
         echo ${{ inputs.salesforce_sfdx_auth_url }} > ./sfdxauthurl.txt
 
+    - name: Should not set use_sf and use_sfdx
+      if: "${{ inputs.use_sfdx }}"=="true" && ${"{ inputs.use_sf }}"=="true"
+      shell: bash
+      run: |
+        echo "ERROR : You ned to set 'use_sf' or 'use_sfdx' to true, but not both"
+        exit 1
+
     - name: Authenticate with SFDX
-      if: ${{ inputs.use_sfdx }} && !${{ inputs.use_sf }}
+      if: "${{ inputs.use_sfdx }}"=="true"
       shell: bash
       run: |
         echo "USING SFDX"
@@ -76,7 +83,7 @@ runs:
         rm -f ./sfdxauthurl.txt
 
     - name: Authenticate with SF
-      if: ${{ inputs.use_sf }} && !${{ inputs.use_sfdx }}
+      if: "${{ inputs.use_sf }}"=="true"
       shell: bash
       run: |
         echo "USING SF"
@@ -90,13 +97,6 @@ runs:
         fi
         sf config set defaultusername=checkout
         rm -f ./sfdxauthurl.txt
-
-    - name: Should not set use_sf and use_sfdx
-      if: (${{ inputs.use_sfdx }} && ${{ inputs.use_sf }}) || (!${{ inputs.use_sfdx }} && !${{ inputs.use_sf }})
-      shell: bash
-      run: |
-        echo "ERROR : You ned to set 'use_sf' or 'use_sfdx' to true, but not both"
-        exit 1
 
     #################################################################################################################################
     # Run command (sfdx or other)
